import type { VercelRequest, VercelResponse } from '@vercel/node';
import { createClient } from '@supabase/supabase-js';

const supabaseAdmin = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export default async function handler(req: VercelRequest, res: VercelResponse) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const { email, company_name } = req.body;

        if (!email || !company_name) {
            return res.status(400).json({ error: 'Email and Company Name are required' });
        }

        // Insert into company_tokens table
        // The token is auto-generated by default in the SQL schema (gen_random_bytes), 
        // but the Supabase JS client returns the inserted row.
        const { data, error } = await supabaseAdmin
            .from('company_tokens')
            .insert({
                email,
                company_name,
                // token is generated by default if not provided, but we can also generate it here if needed.
                // The SQL default `encode(gen_random_bytes(16), 'hex')` handles it.
            })
            .select('token')
            .single();

        if (error) {
            console.error('Supabase error:', error);
            return res.status(500).json({ error: 'Registration failed' });
        }

        return res.status(200).json({ token: data.token });
    } catch (e) {
        console.error(e);
        return res.status(500).json({ error: 'Server error' });
    }
}
